version: '3.4'

services:
  web.login:
    image: ${DOCKER_REGISTRY-}weblogin
    build:
      context: .
      dockerfile: Web.Login/Dockerfile

  api.core:
    image: ${DOCKER_REGISTRY-}apicore
    build:
      context: .
      dockerfile: API.Core/Dockerfile
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:4.2.13
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
