version: '3.4'

services:
  web.login:
    image: ${DOCKER_REGISTRY-}weblogin
    build:
      context: .
      dockerfile: Web.Login/Dockerfile

  api.core:
    image: ${DOCKER_REGISTRY-}apicore
    build:
      context: .
      dockerfile: API.Core/Dockerfile
